import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/client";
import "./globals.css";
import { getQueryClient } from "~/trpc/server";

const dmSans = DM_Sans({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const queryClient = getQueryClient();
	return (
		<html lang="en">
			<body className={`${dmSans.className} antialiased`}>
				<TRPCReactProvider>
					{children}
					<ReactQueryDevtools />
				</TRPCReactProvider>
			</body>
		</html>
	);
}
